{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Quantum Hash Function Performance Analysis"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from main import quantum_hash\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from scipy.stats import entropy\n",
    "from time import perf_counter\n",
    "\n",
    "# Test Avalanche Effect\n",
    "def test_avalanche():\n",
    "    input1 = b\"hello\"\n",
    "    input2 = b\"hellp\"  # 1-bit change\n",
    "    hash1 = quantum_hash(input1)\n",
    "    hash2 = quantum_hash(input2)\n",
    "    \n",
    "    # Calculate bit difference\n",
    "    xor = int.from_bytes(hash1, 'big') ^ int.from_bytes(hash2, 'big')\n",
    "    diff_bits = bin(xor).count('1')\n",
    "    print(f\"Avalanche Effect: {diff_bits/256*100:.2f}% bits changed\")\n",
    "\n",
    "# Test Entropy\n",
    "def test_entropy():\n",
    "    hashes = [quantum_hash(str(i).encode()) for i in range(100)]\n",
    "    bit_dist = np.zeros(256)\n",
    "    \n",
    "    for h in hashes:\n",
    "        for i, byte in enumerate(h):\n",
    "            for j in range(8):\n",
    "                bit_dist[i*8+j] += (byte >> j) & 1\n",
    "    \n",
    "    bit_dist /= len(hashes)\n",
    "    print(f\"Output Entropy: {entropy(bit_dist, base=2):.4f} bits\")\n",
    "    plt.bar(range(256), bit_dist)\n",
    "    plt.title(\"Bit Distribution Across Output\")\n",
    "\n",
    "# Benchmark Performance\n",
    "def benchmark():\n",
    "    sizes = [8, 16, 32, 64, 128, 256]\n",
    "    times = []\n",
    "    \n",
    "    for size in sizes:\n",
    "        data = np.random.bytes(size//8)\n",
    "        start = perf_counter()\n",
    "        quantum_hash(data)\n",
    "        times.append(perf_counter() - start)\n",
    "    \n",
    "    plt.plot(sizes, times)\n",
    "    plt.xlabel(\"Input Size (bits)\")\n",
    "    plt.ylabel(\"Time (s)\")\n",
    "\n",
    "# Run all tests\n",
    "test_avalanche()\n",
    "test_entropy()\n",
    "benchmark()"
   ]
  }
 ]
}
